#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/manaus

PRODUCT_COPY_FILES += \
    vendor/motorola/manaus/proprietary/product/etc/felica/common.cfg:$(TARGET_COPY_OUT_PRODUCT)/etc/felica/common.cfg \
    vendor/motorola/manaus/proprietary/product/etc/felica/mfm.cfg:$(TARGET_COPY_OUT_PRODUCT)/etc/felica/mfm.cfg \
    vendor/motorola/manaus/proprietary/product/etc/felica/mfs.cfg:$(TARGET_COPY_OUT_PRODUCT)/etc/felica/mfs.cfg \
    vendor/motorola/manaus/proprietary/product/etc/permissions/com.motorola.moto-uirefresh.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.moto-uirefresh.xml \
    vendor/motorola/manaus/proprietary/product/etc/permissions/deviceowner-configuration-com.motorola.camera3.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/deviceowner-configuration-com.motorola.camera3.xml \
    vendor/motorola/manaus/proprietary/product/etc/permissions/privapp-permissions-com.motorola.camera3.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.camera3.xml \
    vendor/motorola/manaus/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera3.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.camera3.xml \
    vendor/motorola/manaus/proprietary/system/etc/permissions/com.motorola.motosignature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.motosignature.xml \
    vendor/motorola/manaus/proprietary/system/etc/permissions/moto-core_services.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-core_services.xml \
    vendor/motorola/manaus/proprietary/system/etc/permissions/moto-settings.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-settings.xml \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/031c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/031c0000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/05060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05060000000000000000000000000000.tabin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/05070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05070000000000000000000000000000.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/05070000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05070000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/08080000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08080000000000000000000000000000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/6b3f5fa0f8cf55a7be2582587d62d63a.drbin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/motorola/manaus/proprietary/vendor/app/mcRegistry/ffffffff000000000000000000000003.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/ffffffff000000000000000000000003.tabin \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/ae/mt6879/ParameterDB_ae.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/ae/mt6879/ParameterDB_ae.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/af/mt6879/ParameterDB_af.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/af/mt6879/ParameterDB_af.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/awbsync/mt6879/ParameterDB_awbsync.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/awbsync/mt6879/ParameterDB_awbsync.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/feature/mt6879/ParameterDB_feature.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/feature/mt6879/ParameterDB_feature.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/flash/mt6879/ParameterDB_flash.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/flash/mt6879/ParameterDB_flash.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/flashcali/mt6879/ParameterDB_flashcali.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/flashcali/mt6879/ParameterDB_flashcali.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/mt6879/ParameterDB.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/mt6879/ParameterDB.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/mt6879/top_control_data.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/mt6879/top_control_data.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/pd/mt6879/ParameterDB_pd.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/pd/mt6879/ParameterDB_pd.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/pipeline/mt6879/ParameterDB_pipeline.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/pipeline/mt6879/ParameterDB_pipeline.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/port_select.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/port_select.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tone/mt6879/ParameterDB_tone.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tone/mt6879/ParameterDB_tone.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/default_sensor/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx214_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx334sub_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx481_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx586_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/imx766dual_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_hi1336_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_hi1336_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_hi1336_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_hi1336_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50a_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50a_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50a_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50a_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50e_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50e_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50e_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_ov50e_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_s5kgd2_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_s5kgd2_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_s5kgd2_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_aion_s5kgd2_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_gc02m1b_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_gc02m1b_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_gc02m1b_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_gc02m1b_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_hi1336_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_hi1336_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_hi1336_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_hi1336_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov32c_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov32c_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov32c_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov32c_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov50a_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov50a_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov50a_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_dubai_ov50a_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw_row/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw_row/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw_row/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_hi1336_mipi_raw_row/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw_row/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw_row/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw_row/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov32b_mipi_raw_row/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw_row/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw_row/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw_row/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mot_manaus_ov50a_mipi_raw_row/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mt6879/ISP_info.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/mt6879/ISP_info.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/ov48b_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3m5sx_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6879/ISP_mapping.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6879/ISP_mapping.db \
    vendor/motorola/manaus/proprietary/vendor/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6879/ISP_param.db:$(TARGET_COPY_OUT_VENDOR)/bin/crossbuild/DataSet/SQLiteModule/db/tuning_DB/s5k3p9sp_mipi_raw/mt6879/ISP_param.db \
    vendor/motorola/manaus/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/AudioLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AudioLog_dynamic.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/ap_gain.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain.bin \
    vendor/motorola/manaus/proprietary/vendor/etc/ap_gain_mmul.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain_mmul.bin \
    vendor/motorola/manaus/proprietary/vendor/etc/arcsoft_calibration_u_dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/arcsoft_calibration_u_dc.bin \
    vendor/motorola/manaus/proprietary/vendor/etc/aualgo/aualgo_comp_azpp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/aualgo/aualgo_comp_azpp.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/aualgo/aualgo_sst.conf:$(TARGET_COPY_OUT_VENDOR)/etc/aualgo/aualgo_sst.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/AudioParamOptions_mgvi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_mgvi.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechAcousticShock_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechAcousticShock_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechAcousticShock_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechAcousticShock_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWCommonSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCommonSetting_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWCommonSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCommonSetting_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWCompatibilityCode_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCompatibilityCode_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWCompatibilityCode_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWCompatibilityCode_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/aurisys_config_hifi3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_hifi3.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/aurisys_config_rv.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_rv.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/bstai_hdr_manaus:$(TARGET_COPY_OUT_VENDOR)/etc/bstai_hdr_manaus \
    vendor/motorola/manaus/proprietary/vendor/etc/camera/vidhance.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance.lic \
    vendor/motorola/manaus/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/motorola/manaus/proprietary/vendor/etc/cust_color_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_0.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/cust_color_1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_1.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/cust_color_2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_2.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/cust_color_3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_color_3.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/cust_silky_brightness.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cust_silky_brightness.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/default_pd_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/etc/default_pd_calibration.bin \
    vendor/motorola/manaus/proprietary/vendor/etc/dual_golden_wide.bin:$(TARGET_COPY_OUT_VENDOR)/etc/dual_golden_wide.bin \
    vendor/motorola/manaus/proprietary/vendor/etc/fstb.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/fstb.cfg \
    vendor/motorola/manaus/proprietary/vendor/etc/gbe.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/gbe.cfg \
    vendor/motorola/manaus/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/motorola/manaus/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/motorola/manaus/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/motorola/manaus/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/motorola/manaus/proprietary/vendor/etc/init/motorola.hardware.camera.imgtuner.aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.camera.imgtuner.aidl-service.rc \
    vendor/motorola/manaus/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/motorola/manaus/proprietary/vendor/etc/jiigan/jiigan_model.data:$(TARGET_COPY_OUT_VENDOR)/etc/jiigan/jiigan_model.data \
    vendor/motorola/manaus/proprietary/vendor/etc/libese-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libese-nxp.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nci_100.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci_100.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nci_220.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci_220.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nci_220e.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci_220e.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nci_557.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci_557.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nci_560.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci_560.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nxp-pnscr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp-pnscr.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nxp_220.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_220.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nxp_220e.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_220e.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/libnfc-nxp_560.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_560.conf \
    vendor/motorola/manaus/proprietary/vendor/etc/nfc_calibration.txt:$(TARGET_COPY_OUT_VENDOR)/etc/nfc_calibration.txt \
    vendor/motorola/manaus/proprietary/vendor/etc/permissions/com.motorola.camera3.content.ai.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.camera3.content.ai.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/permissions/com.motorola.camera3.lens.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.camera3.lens.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/permissions/com.motorola.camera3.manaus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.camera3.manaus.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/permissions/com.motorola.camera3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.motorola.camera3.xml \
    vendor/motorola/manaus/proprietary/vendor/etc/sn100u_nfcon.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_nfcon.pnscr \
    vendor/motorola/manaus/proprietary/vendor/etc/sn100u_pnx_ese_cplc.pnscr:$(TARGET_COPY_OUT_VENDOR)/etc/sn100u_pnx_ese_cplc.pnscr \
    vendor/motorola/manaus/proprietary/vendor/etc/tetras/portrait_repair_composite.model:$(TARGET_COPY_OUT_VENDOR)/etc/tetras/portrait_repair_composite.model \
    vendor/motorola/manaus/proprietary/vendor/etc/vhw.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vhw.xml \
    vendor/motorola/manaus/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/motorola/manaus/proprietary/vendor/firmware/NFG1000A_battery_parameter_SB18D87942.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/NFG1000A_battery_parameter_SB18D87942.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/NFG1000A_battery_parameter_SB18D87943.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/NFG1000A_battery_parameter_SB18D87943.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/NFG1000A_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/NFG1000A_firmware.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/WIFI_RAM_CODE_soc7_0_1a_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc7_0_1a_1.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/aw882xx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_acf.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/aw963xx_reg_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw963xx_reg_0.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/aw963xx_reg_evt_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw963xx_reg_evt_0.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/boe_goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/boe_goodix_cfg_group.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/boe_goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/boe_goodix_firmware.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/boe_goodix_test_limits_255.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/boe_goodix_test_limits_255.csv \
    vendor/motorola/manaus/proprietary/vendor/firmware/conninfra.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/conninfra.cfg \
    vendor/motorola/manaus/proprietary/vendor/firmware/focaltech_ts_fw_csot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_csot.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/motorola/manaus/proprietary/vendor/firmware/lib3a.ccu_dummy:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu_dummy \
    vendor/motorola/manaus/proprietary/vendor/firmware/mali_csffw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/mali_csffw_reload.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mali_csffw_reload.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/mot_dw9781.prog:$(TARGET_COPY_OUT_VENDOR)/firmware/mot_dw9781.prog \
    vendor/motorola/manaus/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/motorola/manaus/proprietary/vendor/firmware/soc7_0_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc7_0_ram_bt_1_1_hdr.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/soc7_0_ram_bt_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc7_0_ram_bt_1a_1_hdr.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/soc7_0_ram_bt_1b_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc7_0_ram_bt_1b_1_hdr.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/soc7_0_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc7_0_ram_mcu_1_1_hdr.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/soc7_0_ram_mcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc7_0_ram_mcu_1a_1_hdr.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/soc7_0_ram_mcu_1b_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc7_0_ram_mcu_1b_1_hdr.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/soc7_0_ram_wmmcu_1a_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc7_0_ram_wmmcu_1a_1_hdr.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/tm_goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tm_goodix_cfg_group.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/tm_goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tm_goodix_firmware.bin \
    vendor/motorola/manaus/proprietary/vendor/firmware/tm_goodix_test_limits_255.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/tm_goodix_test_limits_255.csv \
    vendor/motorola/manaus/proprietary/vendor/firmware/txpowerctrl.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl.cfg \
    vendor/motorola/manaus/proprietary/vendor/firmware/txpowerctrl_na.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/txpowerctrl_na.cfg \
    vendor/motorola/manaus/proprietary/vendor/firmware/valhall-1691526.wa:$(TARGET_COPY_OUT_VENDOR)/firmware/valhall-1691526.wa \
    vendor/motorola/manaus/proprietary/vendor/firmware/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi.cfg \
    vendor/motorola/manaus/proprietary/vendor/lib64/arcsoft_portrait_super_night_se_raw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/arcsoft_portrait_super_night_se_raw.bin \
    vendor/motorola/manaus/proprietary/vendor/lib64/arcsoft_super_night_raw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/arcsoft_super_night_raw.bin \
    vendor/motorola/manaus/proprietary/vendor/lib64/arcsoft_super_night_se_raw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/arcsoft_super_night_se_raw.bin

PRODUCT_PACKAGES += \
    com.motorola.hardware.display.panel@1.0 \
    com.motorola.hardware.display.panel@1.1 \
    audio.primary.mediatek \
    fingerprint.goodix.default \
    android.hardware.camera.provider@2.6-impl-mediatek \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    jcos_client \
    lib3a.ae.pipe \
    libAncHumanSegFigureFusion \
    libBSTDSLR \
    libBSTHDRDETECT \
    libBSTMultiExpoGainHDR \
    libBasicModule \
    libRbsFlow \
    libSQLiteModule_VER_ALL \
    libVkLayer_mtk_rt_sdk \
    lib_ainr_enh \
    libancbase \
    libarcsoft_portrait_distortion_correction \
    libarcsoft_portrait_super_night_se_raw \
    libarcsoft_super_night_raw \
    libarcsoft_super_night_se_raw \
    libaualgo_azp_component \
    libaualgo_azp_wrapper \
    libaualgo_foundation \
    libaualgo_sst_component \
    libaudio_param_parser-vnd \
    libc++_shared \
    libcam.seninfn3d \
    libcamalgo.3dnr \
    libcamalgo.WarpMapResizer \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.hdr10p \
    libcamalgo.lmv \
    libcamalgo.mcnr \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.utility \
    libcamalgo.vsdofUtil \
    libcamalgo.warp \
    libdynamiclog \
    libfeaturepolicy \
    libfft_vendor \
    libfgauge_gm30 \
    libgf_hal \
    libheichal \
    libimagebuffer_wrapper \
    libimgsensorca \
    libiqi_bridge \
    libispcameraca \
    liblog_vendor \
    libminiui \
    libmpbase \
    libmtkcam_fdWarpConvert \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_thirdparty.vidhance \
    libmtkisp_metadata \
    libmtkisp_metadata_v2 \
    libnxp_extamp_intf \
    liboem_specific \
    libpn557_fw \
    libpn560_fw \
    libportrait_repair_ppl3_ocl \
    libscltm \
    libsn100u_fw \
    libsn220u_fw \
    libstfactory-vendor \
    libvidhance \
    ls_client \
    ls_nq_client \
    motorola.hardware.camera.imgtuner.aidl-V1-ndk_platform \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.af.assist.models1d \
    lib3a.af.assist.models2d \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.aishutter \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.awbsync \
    lib3a.cculog \
    lib3a.custom.ae \
    lib3a.flash \
    lib3a.flicker \
    lib3a.log \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    lib3a.stat \
    libDBAccessor_ISP \
    libMtkMediaController \
    libSonyIMX519PdafWrapper \
    lib_bsscore \
    libaaa_afassist \
    libaaa_feature \
    libaaa_gma \
    libaaa_ltm \
    libaaa_ltmx \
    libaaa_tnc \
    libaaa_toneutil \
    libacdk \
    libaiawb_fs \
    libaiawb_fs_model \
    libaiawb_moon \
    libaiawb_moon_model \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaiawb_sun_model \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaibc_tuning_p4 \
    libaidepth_tuning \
    libalgo.aosp.log \
    libapudcutils \
    libcam.3a_isp.utils \
    libcam.afmgr \
    libcam.chdr \
    libcam.feature_utils \
    libcam.fw_me_tcy \
    libcam.hal3a.afassitmgr \
    libcam.hal3a.cctsvr.v4l2 \
    libcam.hal3a.ctrl \
    libcam.hal3a.guard \
    libcam.hal3a.ircutdrv \
    libcam.hal3a.lensdrv \
    libcam.hal3a.log \
    libcam.hal3a.lscMgrApi \
    libcam.hal3a.oisdrv \
    libcam.hal3a.ozoomdrv \
    libcam.hal3a.policy \
    libcam.hal3a \
    libcam.hal3a.tofdrv \
    libcam.hal3a.utils \
    libcam.hal3a.v3.ae.v4l2 \
    libcam.hal3a.v3.ai3a_v4l2 \
    libcam.hal3a.v3.awb_v4l2 \
    libcam.hal3a.v3.cac.mgr.v4l2 \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.flash.v4l2 \
    libcam.hal3a.v3.flicker.v4l2 \
    libcam.hal3a.v3.ir.v4l2 \
    libcam.hal3a.v3.lsctbl.v4l2 \
    libcam.hal3a.v3.nvram.v4l2 \
    libcam.hal3a.v3.sensor.v4l2 \
    libcam.hal3a.v3.strobe \
    libcam.hal3a.v3.stt_v4l2 \
    libcam.hal3a.v3.tone.mgr.v4l2 \
    libcam.halisp.TopCtrlMgr \
    libcam.halisp.TuningDataProvider \
    libcam.halisp.TuningDataProviderFactory \
    libcam.halisp.imp.v4l2 \
    libcam.halisp.plugin \
    libcam.halisp.utils \
    libcam.halisp.v4l2 \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.isptuning.v4l2 \
    libcam.peripheralcontroller \
    libcam.tuningcachemgr \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcam_ipc_hal3a_client \
    libcam_ipc_halisp_client \
    libcam_ipc_nvbuf_client \
    libcamalgo.BSSwrapper \
    libcamalgo.Mfbllwrapper \
    libcamalgo.ais2.bss \
    libcamalgo.ais2.mfnr \
    libcamalgo.bss \
    libcamalgo.fus \
    libcamalgo.lsc \
    libcamalgo.mfnr \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.vaidepth \
    libcamalgo.vainr \
    libcamalgo.vsf \
    libcamera.custom.af_assist_buf_mgr \
    libcamera.custom.af_assist_buf_mgr_open \
    libcamera.custom.af_assist_mgr \
    libcamera.custom.af_assist_pdp \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_calibration.core \
    libcameracustom.camera_exif \
    libcameracustom.cfg_setting.core \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.imgsensor.core \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libccd \
    libeffecthal.base \
    libfeature.face \
    libfeature.fwmvp \
    libfeature.hdr10 \
    libfeature.mcnr \
    libfeature.stereo.provider \
    libfeature.vainr.hal \
    libfeature.vsdof.3a_info_provider \
    libfeature.vsdof.hal \
    libfeature_eis \
    libfeature_fsc \
    libfeature_rss \
    libfeature_vrp \
    libfeatureiodrv_mem \
    libfeaturepolicy_dbhandler \
    libgpudataproducer \
    libimgsys_adl \
    libimgsys_cmt \
    libimgsys_daemon \
    libimgsys_dip \
    libimgsys_drvcommon \
    libimgsys_gce \
    libimgsys_main \
    libimgsys_me \
    libimgsys_pqdip \
    libimgsys_sensor \
    libimgsys_system \
    libimgsys_taskhandler \
    libimgsys_tdrhal \
    libimgsys_traw \
    libimgsys_utils \
    libimgsys_v4l2 \
    libimgsys_wpe \
    libispfeature_mtkcam.v4l2 \
    liblpnr \
    libmdla_ut \
    libmfllcore \
    libmgr3a.adapt \
    libmtkcam.atmseventmgr \
    libmtkcam.debugwrapper \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.p2g \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof.wrapper \
    libmtkcam.logicalcaminfoprovider \
    libmtkcam.logicalmodule \
    libmtkcam_aie \
    libmtkcam_android_zslprocessor \
    libmtkcam_buffer_flush \
    libmtkcam_ca \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_camcontroller \
    libmtkcam_camcoordinator \
    libmtkcam_camctrl \
    libmtkcam_coredev \
    libmtkcam_custzone \
    libmtkcam_debugutils \
    libmtkcam_devicemgr \
    libmtkcam_diputils \
    libmtkcam_dma_map \
    libmtkcam_exif \
    libmtkcam_externalisploader \
    libmtkcam_faceResultHandler \
    libmtkcam_grallocutils \
    libmtkcam_hal3a_provider \
    libmtkcam_hal_android_app_cbadaptor \
    libmtkcam_hal_android_common \
    libmtkcam_hal_android_device \
    libmtkcam_hal_android_provider \
    libmtkcam_hal_android_utils \
    libmtkcam_hal_core_app \
    libmtkcam_hal_core_app_cbadaptor \
    libmtkcam_hal_core_device \
    libmtkcam_hal_core_devicesessionpolicy \
    libmtkcam_hal_core_featurepolicy \
    libmtkcam_hal_core_provider \
    libmtkcam_hal_core_utils \
    libmtkcam_hal_custom \
    libmtkcam_hal_custom_provider \
    libmtkcam_hal_hidl_common \
    libmtkcam_hal_hidl_device \
    libmtkcam_hal_hidl_provider \
    libmtkcam_hal_hidl_utils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_hwutils_android \
    libmtkcam_hwutils_poweronoffcontroller \
    libmtkcam_imgbuf_v2 \
    libmtkcam_ipc_core \
    libmtkcam_ipc_wrapper_common_client \
    libmtkcam_ipc_wrapper_common_server \
    libmtkcam_ipc_wrapper_mtk_client \
    libmtkcam_ipc_wrapper_mtk_server \
    libmtkcam_jsonconvertor \
    libmtkcam_jsondata \
    libmtkcam_mapping_mgr \
    libmtkcam_metaconv \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_packutils \
    libmtkcam_pip \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_pipemgr \
    libmtkcam_postprocprovider \
    libmtkcam_prerelease \
    libmtkcam_proc \
    libmtkcam_request_requlator \
    libmtkcam_salmgr \
    libmtkcam_sensorcontrol \
    libmtkcam_simager \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_thirdparty.core \
    libmtkcam_thirdparty.customer \
    libmtkcam_thirdparty.customzone \
    libmtkcam_thirdparty.mtk \
    libmtkcam_thirdparty \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libmtkcm_ipc_dummy \
    libpda_usdriver \
    libstereoinfoaccessor_vsdof \
    libvainr_model \
    mot_manaus_hi1336_mipi_raw_IdxMgr \
    mot_manaus_hi1336_mipi_raw_row_IdxMgr \
    mot_manaus_hi1336_mipi_raw_row_tuning \
    mot_manaus_hi1336_mipi_raw_tuning \
    mot_manaus_ov32b_mipi_raw_IdxMgr \
    mot_manaus_ov32b_mipi_raw_row_IdxMgr \
    mot_manaus_ov32b_mipi_raw_row_tuning \
    mot_manaus_ov32b_mipi_raw_tuning \
    mot_manaus_ov50a_mipi_raw_IdxMgr \
    mot_manaus_ov50a_mipi_raw_row_IdxMgr \
    mot_manaus_ov50a_mipi_raw_row_tuning \
    mot_manaus_ov50a_mipi_raw_tuning \
    mtk000_mipi_raw_IdxMgr \
    mtk000_mipi_raw_tuning \
    se_extn_client \
    libmsstwrapper \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    MotoSignatureApp \
    MotCamera3AI \
    MobileFeliCaClient \
    MotCamera4 \
    MotorolaSettingsProvider \
    com.motorola.motosignature \
    moto-core_services \
    moto-settings \
    manifest_cameraprovider.xml \
    motorola.hardware.camera.imgtuner.aidl.xml \
    SN1X0__RF-On.txt \
    ParameterDB_awb.db \
    fuelgauged \
    fuelgauged_nvram \
    android.hardware.secure_element@1.2-service-mediatek \
    motorola.hardware.camera.imgtuner.aidl-service \
    camerahalserver \
    dumpfaultd.mt6879 \
    nxpnfcinfo \
    pnscr \
    pnscr_cal \
    sns_mot_client \
    motsettings

PRODUCT_PACKAGES += \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_ae_ParameterDB_ae_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_af_ParameterDB_af_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_awb_ParameterDB_awb_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_awbsync_ParameterDB_awbsync_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_feature_ParameterDB_feature_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_flash_ParameterDB_flash_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_flashcali_ParameterDB_flashcali_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_ParameterDB_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_top_control_data_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_pd_ParameterDB_pd_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_pipeline_ParameterDB_pipeline_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tone_ParameterDB_tone_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_default_sensor_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_default_sensor_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx214_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx214_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334sub_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx334sub_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx481_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx481_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx586_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx586_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766dual_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_imx766dual_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_hi1336_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_hi1336_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_ov50a_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_ov50a_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_ov50e_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_ov50e_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_s5kgd2_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_aion_s5kgd2_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_gc02m1b_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_gc02m1b_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_hi1336_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_hi1336_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_ov32c_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_ov32c_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_ov50a_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_dubai_ov50a_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_hi1336_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_hi1336_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_hi1336_mipi_raw_row_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_hi1336_mipi_raw_row_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov32b_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov32b_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov32b_mipi_raw_row_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov32b_mipi_raw_row_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov50a_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov50a_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov50a_mipi_raw_row_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_mot_manaus_ov50a_mipi_raw_row_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ISP_info_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ov48b_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_ov48b_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3m5sx_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3m5sx_mipi_raw_ISP_param_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3p9sp_mipi_raw_ISP_mapping_db \
    vendor_bin_crossbuild_DataSet_SQLiteModule_db_tuning_DB_s5k3p9sp_mipi_raw_ISP_param_db \
    vendor_bin_hw_camerahalserver \
    vendor_bin_dumpfaultd \
    vendor_lib64_hw_audio_primary_mt6879_so \
    vendor_lib64_hw_android_hardware_camera_provider@2_6-impl-mediatek_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_atms@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_bgservice@1_1-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_isphal@1_1-impl_so \
    vendor_lib64_lib3a_ae_core_so \
    vendor_lib64_lib3a_ae_so \
    vendor_lib64_lib3a_af_assist_models1d_so \
    vendor_lib64_lib3a_af_assist_models2d_so \
    vendor_lib64_lib3a_af_assist_so \
    vendor_lib64_lib3a_af_assist_utils_so \
    vendor_lib64_lib3a_af_core_so \
    vendor_lib64_lib3a_af_so \
    vendor_lib64_lib3a_aishutter_so \
    vendor_lib64_lib3a_alsflicker_so \
    vendor_lib64_lib3a_awb_core_so \
    vendor_lib64_lib3a_awbsync_so \
    vendor_lib64_lib3a_cculog_so \
    vendor_lib64_lib3a_custom_ae_so \
    vendor_lib64_lib3a_flash_so \
    vendor_lib64_lib3a_flicker_so \
    vendor_lib64_lib3a_log_so \
    vendor_lib64_lib3a_sensors_color_so \
    vendor_lib64_lib3a_sensors_flicker_so \
    vendor_lib64_lib3a_stat_so \
    vendor_lib64_libDBAccessor_ISP_so \
    vendor_lib64_libMtkMediaController_so \
    vendor_lib64_libSonyIMX519PdafWrapper_so \
    vendor_lib64_lib_bsscore_so \
    vendor_lib64_libaaa_afassist_so \
    vendor_lib64_libaaa_feature_so \
    vendor_lib64_libaaa_gma_so \
    vendor_lib64_libaaa_ltm_so \
    vendor_lib64_libaaa_ltmx_so \
    vendor_lib64_libaaa_tnc_so \
    vendor_lib64_libaaa_toneutil_so \
    vendor_lib64_libacdk_so \
    vendor_lib64_libaiawb_fs_so \
    vendor_lib64_libaiawb_fs_model_so \
    vendor_lib64_libaiawb_moon_so \
    vendor_lib64_libaiawb_moon_model_so \
    vendor_lib64_libaiawb_p1ggm_so \
    vendor_lib64_libaiawb_sun_so \
    vendor_lib64_libaiawb_sun_model_so \
    vendor_lib64_libaibc_tuning_so \
    vendor_lib64_libaibc_tuning_p2_so \
    vendor_lib64_libaibc_tuning_p3_so \
    vendor_lib64_libaibc_tuning_p4_so \
    vendor_lib64_libaidepth_tuning_so \
    vendor_lib64_libalgo_aosp_log_so \
    vendor_lib64_libapudcutils_so \
    vendor_lib64_libcam_3a_isp_utils_so \
    vendor_lib64_libcam_afmgr_so \
    vendor_lib64_libcam_chdr_so \
    vendor_lib64_libcam_feature_utils_so \
    vendor_lib64_libcam_fw_me_tcy_so \
    vendor_lib64_libcam_hal3a_afassitmgr_so \
    vendor_lib64_libcam_hal3a_cctsvr_v4l2_so \
    vendor_lib64_libcam_hal3a_ctrl_so \
    vendor_lib64_libcam_hal3a_guard_so \
    vendor_lib64_libcam_hal3a_ircutdrv_so \
    vendor_lib64_libcam_hal3a_lensdrv_so \
    vendor_lib64_libcam_hal3a_log_so \
    vendor_lib64_libcam_hal3a_lscMgrApi_so \
    vendor_lib64_libcam_hal3a_oisdrv_so \
    vendor_lib64_libcam_hal3a_ozoomdrv_so \
    vendor_lib64_libcam_hal3a_policy_so \
    vendor_lib64_libcam_hal3a_so \
    vendor_lib64_libcam_hal3a_tofdrv_so \
    vendor_lib64_libcam_hal3a_utils_so \
    vendor_lib64_libcam_hal3a_v3_ae_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_ai3a_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_awb_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_cac_mgr_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_dng_so \
    vendor_lib64_libcam_hal3a_v3_flash_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_flicker_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_ir_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_lsctbl_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_nvram_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_sensor_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_strobe_so \
    vendor_lib64_libcam_hal3a_v3_stt_v4l2_so \
    vendor_lib64_libcam_hal3a_v3_tone_mgr_v4l2_so \
    vendor_lib64_libcam_halisp_TopCtrlMgr_so \
    vendor_lib64_libcam_halisp_TuningDataProvider_so \
    vendor_lib64_libcam_halisp_TuningDataProviderFactory_so \
    vendor_lib64_libcam_halisp_imp_v4l2_so \
    vendor_lib64_libcam_halisp_plugin_so \
    vendor_lib64_libcam_halisp_utils_so \
    vendor_lib64_libcam_halisp_v4l2_so \
    vendor_lib64_libcam_halsensor_hwintegration_so \
    vendor_lib64_libcam_halsensor_so \
    vendor_lib64_libcam_isptuning_v4l2_so \
    vendor_lib64_libcam_peripheralcontroller_so \
    vendor_lib64_libcam_tuningcachemgr_so \
    vendor_lib64_libcam_utils_sensorprovider_so \
    vendor_lib64_libcam_vhdr_so \
    vendor_lib64_libcam_ipc_hal3a_client_so \
    vendor_lib64_libcam_ipc_halisp_client_so \
    vendor_lib64_libcam_ipc_nvbuf_client_so \
    vendor_lib64_libcamalgo_BSSwrapper_so \
    vendor_lib64_libcamalgo_Mfbllwrapper_so \
    vendor_lib64_libcamalgo_ais2_bss_so \
    vendor_lib64_libcamalgo_ais2_mfnr_so \
    vendor_lib64_libcamalgo_bss_so \
    vendor_lib64_libcamalgo_fus_so \
    vendor_lib64_libcamalgo_lsc_so \
    vendor_lib64_libcamalgo_mfnr_so \
    vendor_lib64_libcamalgo_platform2_so \
    vendor_lib64_libcamalgo_rotate_so \
    vendor_lib64_libcamalgo_vaidepth_so \
    vendor_lib64_libcamalgo_vainr_so \
    vendor_lib64_libcamalgo_vsf_so \
    vendor_lib64_libcamera_custom_af_assist_buf_mgr_so \
    vendor_lib64_libcamera_custom_af_assist_buf_mgr_open_so \
    vendor_lib64_libcamera_custom_af_assist_mgr_so \
    vendor_lib64_libcamera_custom_af_assist_pdp_so \
    vendor_lib64_libcamera_customae_so \
    vendor_lib64_libcamera_customaf_so \
    vendor_lib64_libcamera_customawb_so \
    vendor_lib64_libcamera_customflk_so \
    vendor_lib64_libcameracustom_camera_3a_so \
    vendor_lib64_libcameracustom_camera_isp_so \
    vendor_lib64_libcameracustom_camera_sensors_so \
    vendor_lib64_libcameracustom_camera_calibration_core_so \
    vendor_lib64_libcameracustom_camera_exif_so \
    vendor_lib64_libcameracustom_cfg_setting_core_so \
    vendor_lib64_libcameracustom_eis_so \
    vendor_lib64_libcameracustom_flashlight_so \
    vendor_lib64_libcameracustom_imgsensor_core_so \
    vendor_lib64_libcameracustom_lens_so \
    vendor_lib64_libcameracustom_plugin_so \
    vendor_lib64_libcameracustom_so \
    vendor_lib64_libccd_so \
    vendor_lib64_libeffecthal_base_so \
    vendor_lib64_libfeature_face_so \
    vendor_lib64_libfeature_fwmvp_so \
    vendor_lib64_libfeature_hdr10_so \
    vendor_lib64_libfeature_mcnr_so \
    vendor_lib64_libfeature_stereo_provider_so \
    vendor_lib64_libfeature_vainr_hal_so \
    vendor_lib64_libfeature_vsdof_3a_info_provider_so \
    vendor_lib64_libfeature_vsdof_hal_so \
    vendor_lib64_libfeature_eis_so \
    vendor_lib64_libfeature_fsc_so \
    vendor_lib64_libfeature_rss_so \
    vendor_lib64_libfeature_vrp_so \
    vendor_lib64_libfeatureiodrv_mem_so \
    vendor_lib64_libfeaturepolicy_dbhandler_so \
    vendor_lib64_libgpudataproducer_so \
    vendor_lib64_libimgsys_adl_so \
    vendor_lib64_libimgsys_cmt_so \
    vendor_lib64_libimgsys_daemon_so \
    vendor_lib64_libimgsys_dip_so \
    vendor_lib64_libimgsys_drvcommon_so \
    vendor_lib64_libimgsys_gce_so \
    vendor_lib64_libimgsys_main_so \
    vendor_lib64_libimgsys_me_so \
    vendor_lib64_libimgsys_pqdip_so \
    vendor_lib64_libimgsys_sensor_so \
    vendor_lib64_libimgsys_system_so \
    vendor_lib64_libimgsys_taskhandler_so \
    vendor_lib64_libimgsys_tdrhal_so \
    vendor_lib64_libimgsys_traw_so \
    vendor_lib64_libimgsys_utils_so \
    vendor_lib64_libimgsys_v4l2_so \
    vendor_lib64_libimgsys_wpe_so \
    vendor_lib64_libispfeature_mtkcam_v4l2_so \
    vendor_lib64_liblpnr_so \
    vendor_lib64_libmdla_ut_so \
    vendor_lib64_libmfllcore_so \
    vendor_lib64_libmgr3a_adapt_so \
    vendor_lib64_libmtkcam_atmseventmgr_so \
    vendor_lib64_libmtkcam_debugwrapper_so \
    vendor_lib64_libmtkcam_eventcallback_so \
    vendor_lib64_libmtkcam_featurepipe_capture_so \
    vendor_lib64_libmtkcam_featurepipe_depthmap_so \
    vendor_lib64_libmtkcam_featurepipe_p2g_so \
    vendor_lib64_libmtkcam_featurepipe_streaming_so \
    vendor_lib64_libmtkcam_featurepipe_vsdof_wrapper_so \
    vendor_lib64_libmtkcam_logicalcaminfoprovider_so \
    vendor_lib64_libmtkcam_logicalmodule_so \
    vendor_lib64_libmtkcam_aie_so \
    vendor_lib64_libmtkcam_android_zslprocessor_so \
    vendor_lib64_libmtkcam_buffer_flush_so \
    vendor_lib64_libmtkcam_ca_so \
    vendor_lib64_libmtkcam_calibration_convertor_so \
    vendor_lib64_libmtkcam_calibration_provider_so \
    vendor_lib64_libmtkcam_camcontroller_so \
    vendor_lib64_libmtkcam_camcoordinator_so \
    vendor_lib64_libmtkcam_camctrl_so \
    vendor_lib64_libmtkcam_coredev_so \
    vendor_lib64_libmtkcam_custzone_so \
    vendor_lib64_libmtkcam_debugutils_so \
    vendor_lib64_libmtkcam_devicemgr_so \
    vendor_lib64_libmtkcam_diputils_so \
    vendor_lib64_libmtkcam_dma_map_so \
    vendor_lib64_libmtkcam_exif_so \
    vendor_lib64_libmtkcam_externalisploader_so \
    vendor_lib64_libmtkcam_faceResultHandler_so \
    vendor_lib64_libmtkcam_grallocutils_so \
    vendor_lib64_libmtkcam_hal3a_provider_so \
    vendor_lib64_libmtkcam_hal_android_app_cbadaptor_so \
    vendor_lib64_libmtkcam_hal_android_common_so \
    vendor_lib64_libmtkcam_hal_android_device_so \
    vendor_lib64_libmtkcam_hal_android_provider_so \
    vendor_lib64_libmtkcam_hal_android_utils_so \
    vendor_lib64_libmtkcam_hal_core_app_so \
    vendor_lib64_libmtkcam_hal_core_app_cbadaptor_so \
    vendor_lib64_libmtkcam_hal_core_device_so \
    vendor_lib64_libmtkcam_hal_core_devicesessionpolicy_so \
    vendor_lib64_libmtkcam_hal_core_featurepolicy_so \
    vendor_lib64_libmtkcam_hal_core_provider_so \
    vendor_lib64_libmtkcam_hal_core_utils_so \
    vendor_lib64_libmtkcam_hal_custom_so \
    vendor_lib64_libmtkcam_hal_custom_provider_so \
    vendor_lib64_libmtkcam_hal_hidl_common_so \
    vendor_lib64_libmtkcam_hal_hidl_device_so \
    vendor_lib64_libmtkcam_hal_hidl_provider_so \
    vendor_lib64_libmtkcam_hal_hidl_utils_so \
    vendor_lib64_libmtkcam_hwnode_so \
    vendor_lib64_libmtkcam_hwutils_so \
    vendor_lib64_libmtkcam_hwutils_android_so \
    vendor_lib64_libmtkcam_hwutils_poweronoffcontroller_so \
    vendor_lib64_libmtkcam_imgbuf_v2_so \
    vendor_lib64_libmtkcam_ipc_core_so \
    vendor_lib64_libmtkcam_ipc_wrapper_common_client_so \
    vendor_lib64_libmtkcam_ipc_wrapper_common_server_so \
    vendor_lib64_libmtkcam_ipc_wrapper_mtk_client_so \
    vendor_lib64_libmtkcam_ipc_wrapper_mtk_server_so \
    vendor_lib64_libmtkcam_jsonconvertor_so \
    vendor_lib64_libmtkcam_jsondata_so \
    vendor_lib64_libmtkcam_mapping_mgr_so \
    vendor_lib64_libmtkcam_metaconv_so \
    vendor_lib64_libmtkcam_metadata_so \
    vendor_lib64_libmtkcam_metastore_so \
    vendor_lib64_libmtkcam_modulefactory_custom_so \
    vendor_lib64_libmtkcam_modulefactory_utils_so \
    vendor_lib64_libmtkcam_modulehelper_so \
    vendor_lib64_libmtkcam_packutils_so \
    vendor_lib64_libmtkcam_pip_so \
    vendor_lib64_libmtkcam_pipeline_so \
    vendor_lib64_libmtkcam_pipeline_fbm_so \
    vendor_lib64_libmtkcam_pipelinemodel_capture_so \
    vendor_lib64_libmtkcam_pipelinemodel_session_so \
    vendor_lib64_libmtkcam_pipelinemodel_utils_so \
    vendor_lib64_libmtkcam_pipelinepolicy-security_so \
    vendor_lib64_libmtkcam_pipelinepolicy-smvr_so \
    vendor_lib64_libmtkcam_pipelinepolicy_so \
    vendor_lib64_libmtkcam_pipelinepolicy_factory_so \
    vendor_lib64_libmtkcam_pipemgr_so \
    vendor_lib64_libmtkcam_postprocprovider_so \
    vendor_lib64_libmtkcam_prerelease_so \
    vendor_lib64_libmtkcam_proc_so \
    vendor_lib64_libmtkcam_request_requlator_so \
    vendor_lib64_libmtkcam_salmgr_so \
    vendor_lib64_libmtkcam_sensorcontrol_so \
    vendor_lib64_libmtkcam_simager_so \
    vendor_lib64_libmtkcam_stdutils_so \
    vendor_lib64_libmtkcam_streamutils_so \
    vendor_lib64_libmtkcam_synchelper_so \
    vendor_lib64_libmtkcam_sysutils_so \
    vendor_lib64_libmtkcam_thirdparty_core_so \
    vendor_lib64_libmtkcam_thirdparty_customer_so \
    vendor_lib64_libmtkcam_thirdparty_customzone_so \
    vendor_lib64_libmtkcam_thirdparty_mtk_so \
    vendor_lib64_libmtkcam_thirdparty_so \
    vendor_lib64_libmtkcam_tuning_utils_so \
    vendor_lib64_libmtkcam_ulog_so \
    vendor_lib64_libmtkcm_ipc_dummy_so \
    vendor_lib64_libpda_usdriver_so \
    vendor_lib64_libstereoinfoaccessor_vsdof_so \
    vendor_lib64_libvainr_model_so \
    vendor_lib64_mot_manaus_hi1336_mipi_raw_IdxMgr_so \
    vendor_lib64_mot_manaus_hi1336_mipi_raw_row_IdxMgr_so \
    vendor_lib64_mot_manaus_hi1336_mipi_raw_row_tuning_so \
    vendor_lib64_mot_manaus_hi1336_mipi_raw_tuning_so \
    vendor_lib64_mot_manaus_ov32b_mipi_raw_IdxMgr_so \
    vendor_lib64_mot_manaus_ov32b_mipi_raw_row_IdxMgr_so \
    vendor_lib64_mot_manaus_ov32b_mipi_raw_row_tuning_so \
    vendor_lib64_mot_manaus_ov32b_mipi_raw_tuning_so \
    vendor_lib64_mot_manaus_ov50a_mipi_raw_IdxMgr_so \
    vendor_lib64_mot_manaus_ov50a_mipi_raw_row_IdxMgr_so \
    vendor_lib64_mot_manaus_ov50a_mipi_raw_row_tuning_so \
    vendor_lib64_mot_manaus_ov50a_mipi_raw_tuning_so \
    vendor_lib64_mtk000_mipi_raw_IdxMgr_so \
    vendor_lib64_mtk000_mipi_raw_tuning_so
